model_type: "mlp"  # mlp, gcn, schnet
defaults:
  #- preprocessor: preprocessor; put later, val size.......
  - tuning: mlp
  #- override hydra/launcher: joblib
  - _self_



random_state: 42
exp_name: qm9
run_tuning_name: tuning
