model_type: "mlp"  # mlp, gcn, schnet
defaults:
  - shared/training
  - shared/tuning 
  - preprocessor: preprocessor
  - tuning: mlp
  - override hydra/launcher: joblib
  - _self_



random_state: 42
exp_name: qm9
run_tuning_name: tuning
hydra:
  launcher:
    n_jobs: 2