model_type: "mlp"  # mlp, gcn, schnet
defaults:
  #- preprocessor: preprocessor
  #- tuning: ${model_type}
  - tuning: mlp
  #- evaluation: evaluation
  #- override hydra/launcher: joblib
  - _self_



random_state: 42
experiment_name: qm9
